### Data Encoding

1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

#### Nominal/OHE Encoding
One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using one hot encoding as follows:

1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

### Disadvantages

1. If a feature has many categories, OHE creates many new columns. (If a feature has many categories, OHE creates many new columns.)

2. Most values in the new columns are 0, with only one 1 per row. This creates sparse matrices, which can slow down some algorithms and it leads to overfiting.

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.DataFrame({
  'color': ['red','blue','green','green','red','blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
# Create an instance of OneHotEncoder
encoder = OneHotEncoder()

In [9]:
# Perform fit and transform
# fit_transform() learns from the data and immediately applies the transformation to it.
# In One-Hot Encoding, fit_transform() first learns all categories in the column and then converts them into binary columns at the same time.

encoded = encoder.fit_transform(df[['color']]).toarray()

In [10]:
import pandas as pd
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [11]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [12]:
# For new data
encoder.transform([['blue']]).toarray()

d:\Python Work\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [13]:
pd.concat([df,encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0